apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogueservice
  labels:
    app: productcatalogueservice
spec:
  selector:
    matchLabels:
      app: productcatalogueservice
  template:
    metadata:
      labels:
        app: productcatalogueservice
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.0
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogueservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogueservice
  ports:
    - port: 3550
      targetPort: 3550

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogueservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogueservice
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50