apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

# Ingress patch for all 11 services
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: microservice-ingress
