apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: shippingservice
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/shippingservice:v0.1.0
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: shippingservice
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - protocol: TCPA
      port: 50051
      targetPort: 50051
